### ISSUE TITLE
ZeptoProgram doesn't work with the latest plugin XMLs

### ISSUE THREAD

**Issue by ivankravets** [smartanthill/zepto-compiler#2]
See SmartAnthill Embedded plugins: https://github.com/smartanthill/smartanthill2_0-embedded/tree/develop/firmware/src/plugins
## Program

``` is
return Ping.Execute();
```
## Plugin

https://github.com/smartanthill/smartanthill2_0-embedded/blob/develop/firmware/src/plugins/ping/manifest.xml
## Exception

```
015-07-18 21:54:51+0300 [api] Received 'GET' request with key 'device.128.Ping' and data={}
2015-07-18 21:54:51+0300 [api.rest#error] Unhandled Error
    Traceback (most recent call last):
      File "smartanthill2_0/.tox/develop/lib/python2.7/site-packages/twisted/web/http.py", line 823, in requestReceived
        self.process()
      File "smartanthill2_0/.tox/develop/lib/python2.7/site-packages/twisted/web/server.py", line 189, in process
        self.render(resrc)
      File "smartanthill2_0/.tox/develop/lib/python2.7/site-packages/twisted/web/server.py", line 238, in render
        body = resrc.render(self)
      File "smartanthill2_0/smartanthill/api/rest.py", line 85, in render
        action, request_key, data)
    --- <exception caught here> ---
      File "smartanthill2_0/.tox/develop/lib/python2.7/site-packages/twisted/internet/defer.py", line 150, in maybeDeferred
        result = f(*args, **kw)
      File "smartanthill2_0/smartanthill/api/service.py", line 77, in request
        return hobj.handle(data)
      File "smartanthill2_0/smartanthill/device/api.py", line 39, in handle
        self._bodypart_name, data)
      File "smartanthill2_0/smartanthill/device/device.py", line 76, in execute_bodypart
        return self.run_program(program, request_fields)
      File "smartanthill2_0/smartanthill/device/device.py", line 80, in run_program
        opcode = zp.compile(parameters)
      File "zepto-compiler/origin/smartanthill_zc/api.py", line 158, in compile
        compiler, self._bodyparts, Ctx.BODYPART)
      File "zepto-compiler/origin/smartanthill_zc/parse_xml.py", line 42, in create_bodyparts
        z_plugin.get_response_fields())
      File "zepto-compiler/origin/smartanthill_zc/parse_xml.py", line 185, in _make_plugin
        reply = _make_reply_message_type(compiler, manager, ctx, reply_fields)
      File "zepto-compiler/origin/smartanthill_zc/parse_xml.py", line 220, in _make_reply_message_type
        field = _make_reply_member(compiler, manager, ctx, current)
      File "zepto-compiler/origin/smartanthill_zc/parse_xml.py", line 234, in _make_reply_member
        field = _make_reply_field_type(compiler, manager, ctx, att)
      File "zepto-compiler/origin/smartanthill_zc/parse_xml.py", line 252, in _make_reply_field_type
        encoding, min_v, max_v = _get_enconding_min_max(compiler, ctx, att)
      File "zepto-compiler/origin/smartanthill_zc/parse_xml.py", line 303, in _get_enconding_min_max
        assert False
    exceptions.AssertionError:
```

**Comment by marcosbracco** [comment]
Yes, 'encoded-uint[max=1]' is not recognized as a valid type, as last plugin description I saw only allowed 'encoded-unsigned-int[max=2]' and 'encoded-unsigned-int[max=4]'. Also, only for 2 and 4.
Do we have an up-to-date list of valids types that should be allowed?

**Comment by nobugs-hare** [comment]
Which syntax to support is up to you/Ivan, but support for
Encoded-Unsigned-Int<max=1> (as well as for it's -Signed- counterpart) is
necessary (unlike simple byte, these can be seamlessly expanded later if
necessary).

**Comment by marcosbracco** [comment]
Yes, I see now that http://docs.smartanthill.org/en/latest/design-documents/smartanthill-plugins.html
has been updated the syntax.

**Comment by ivankravets** [comment]
Problem still exists

```
      File "smartanthill2_0/smartanthill/device/device.py", line 81, in run_program
        opcode = zp.compile(parameters)
      File "smartanthill-zepto-compiler/origin/smartanthill_zc/api.py", line 171, in compile
        process_syntax_tree(compiler, root)
      File "smartanthill-zepto-compiler/origin/smartanthill_zc/compiler.py", line 153, in process_syntax_tree
        compiler.resolve_node(root)
      File "smartanthill-zepto-compiler/origin/smartanthill_zc/compiler.py", line 106, in resolve_node
        node.resolve(self)
      File "smartanthill-zepto-compiler/origin/smartanthill_zc/node.py", line 399, in resolve
        compiler.resolve_node(self.child_source_program)
      File "smartanthill-zepto-compiler/origin/smartanthill_zc/compiler.py", line 106, in resolve_node
        node.resolve(self)
      File "smartanthill-zepto-compiler/origin/smartanthill_zc/node.py", line 475, in resolve
        compiler.resolve_node(self.child_statement_list)
      File "smartanthill-zepto-compiler/origin/smartanthill_zc/compiler.py", line 106, in resolve_node
        node.resolve(self)
      File "smartanthill-zepto-compiler/origin/smartanthill_zc/statement.py", line 51, in resolve
        compiler.resolve_node(stmt)
      File "smartanthill-zepto-compiler/origin/smartanthill_zc/compiler.py", line 106, in resolve_node
        node.resolve(self)
      File "smartanthill-zepto-compiler/origin/smartanthill_zc/statement.py", line 145, in resolve
        resolve_expression(compiler, self, 'child_expression')
      File "smartanthill-zepto-compiler/origin/smartanthill_zc/node.py", line 200, in resolve_expression
        replacement = expr.resolve_expr(compiler)
      File "smartanthill-zepto-compiler/origin/smartanthill_zc/expression.py", line 46, in resolve_expr
        self.set_type(self._declaration.get_type())
    exceptions.AttributeError: 'FunctionCallExprNode' object has no attribute '_declaration'
```

**Comment by marcosbracco** [comment]
It seems your are calling 'BodyPartName()' as a function instead of 'BodyPartName.Execute()' using 'Execute()' method.
Will bodypart be called as functions? or will be used as 'Execute(..)' methods?
Should I make function like call work? Or report decent error instead of horrible assert?

**Comment by ivankravets** [comment]
Thanks, you're right. Just fixed it! Looks like it works now!
